### ISSUE TITLE
Can not connect thermal printer

### ISSUE THREAD

**Issue by maxtran88** [CodeFeel/PrinterSDK#1]
Hi owner.
Thank you for your sdk. But I can not connect with my thermal printer.
I got this error:

```
2022-01-23 20:50:45.449003+0700 HYDemo[17125:3633506] [CoreBluetooth] API MISUSE: <CBCentralManager: 0x280225300> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported
2022-01-23 20:50:45.476559+0700 HYDemo[17125:3633506] [CoreBluetooth] API MISUSE: <CBCentralManager: 0x280225300> can only accept this command while in the powered on state

```

Could you please check? Many thanks!

**Comment by CodeFeel** [comment]
Please try to connect your thermal printer with Swift-Demo in Example

**Comment by maxtran88** [comment]
I tried both Swift and ObjC and got this message.
I tried version 1.4.0, still can not connect but does not received this message.

**Comment by CodeFeel** [comment]
Ok, I see, I want to know what brand of printer you are using?

**Comment by CodeFeel** [comment]
Is the phone bluetooth turned on?

**Comment by maxtran88** [comment]
https://www.google.com/search?q=apos+p100

Here is my printer.
Of course, I turned it on.

**Comment by maxtran88** [comment]
I can connect successfully with this framework.
https://github.com/KevinGong2013/Printer

**Comment by CodeFeel** [comment]
There is a connection check in the SDK. Currently, only the printers of Xiamen Hanyin Electronic Technology Co., Ltd. can be connected.

**Comment by maxtran88** [comment]
@CodeFeel 
Could you please make it can connect to other kind of printers?

**Comment by CodeFeel** [comment]
I'm sorry, I'm afraid this won't work;
If you use our company's printer, this is ok
